import { Gender, InterestedIn, RelationshipIntention, Interest } from '../src/types';

export interface SeedUserProfile {
  email: string;
  firstName: string;
  age: number;
  birthDate: string;
  gender: Gender;
  interestedIn: InterestedIn;
  city: string;
  locationLat: number;
  locationLng: number;
  bio: string;
  occupation: string;
  education: string;
  height: string;
  languages: string[];
  relationshipIntention: RelationshipIntention;
  photos: string[];
  interests: string[];
  isVerified: boolean;
  isDemo?: boolean;
  isAdult?: boolean;
  datingIntent?: string;
  relationshipPreference?: string;
}

export const INITIAL_INTERESTS: Interest[] = [
  { id: 'int-1', name: 'Indie Music', category: 'music', icon: 'Headphones' },
  { id: 'int-2', name: 'Specialty Coffee', category: 'food', icon: 'Coffee' },
  { id: 'int-3', name: 'Hiking & Camping', category: 'sports', icon: 'Mountain' },
  { id: 'int-4', name: 'Film Photography', category: 'creativity', icon: 'Camera' },
  { id: 'int-5', name: 'Modern Art', category: 'creativity', icon: 'Palette' },
  { id: 'int-6', name: 'Yoga & Pilates', category: 'lifestyle', icon: 'Smile' },
  { id: 'int-7', name: 'Book Club', category: 'lifestyle', icon: 'Book' },
  { id: 'int-8', name: 'Sourdough & Cooking', category: 'food', icon: 'Utensils' },
  { id: 'int-9', name: 'Electronic Music', category: 'music', icon: 'Radio' },
  { id: 'int-10', name: 'Dog Lover', category: 'lifestyle', icon: 'Heart' },
  { id: 'int-11', name: 'Cat Person', category: 'lifestyle', icon: 'Heart' },
  { id: 'int-12', name: 'Rock Climbing', category: 'sports', icon: 'Compass' },
  { id: 'int-13', name: 'Vintage Thrift', category: 'lifestyle', icon: 'ShoppingBag' },
  { id: 'int-14', name: 'Wine Tasting', category: 'food', icon: 'Wine' },
  { id: 'int-15', name: 'Board Games', category: 'entertainment', icon: 'Dice' },
  { id: 'int-16', name: 'Anime & Manga', category: 'entertainment', icon: 'Tv' },
  { id: 'int-17', name: 'Tech & Startups', category: 'creativity', icon: 'Laptop' },
  { id: 'int-18', name: 'Running / 10k', category: 'sports', icon: 'Zap' },
  { id: 'int-19', name: 'Travel & Backpacking', category: 'lifestyle', icon: 'Plane' },
  { id: 'int-20', name: 'Bouldering', category: 'sports', icon: 'Award' },
];

export const SEED_PROFILES: SeedUserProfile[] = [
  // ================= 15 FEMALE FICTIONAL DEMO PROFILES =================
  {
    email: 'aanya@vibematch.app',
    firstName: 'Aanya',
    age: 23,
    birthDate: '2003-03-14',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Pune',
    locationLat: 18.5204,
    locationLng: 73.8567,
    bio: 'Software engineer by day, cafe explorer by dusk. Looking for someone to join me for filter coffee in FC Road or weekend treks in the Sahyadris 🌿☕',
    occupation: 'Full Stack Engineer at Tech Hub',
    education: 'COEP Technological University',
    height: '5\'5" (165cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'Long-term partner',
    datingIntent: 'Long-term dating & romance',
    relationshipPreference: 'Exclusive dating',
    photos: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Specialty Coffee', 'Indie Music', 'Hiking & Camping', 'Tech & Startups'],
    isVerified: true,
    isDemo: true,
    isAdult: true,
  },
  {
    email: 'neha@vibematch.app',
    firstName: 'Neha',
    age: 25,
    birthDate: '2001-07-22',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Nashik',
    locationLat: 19.9975,
    locationLng: 73.7898,
    bio: 'Viticulturist and wine enthusiast based in the wine capital. Love golden hour vineyard sunsets, live acoustic sets, and honest conversations over cheese boards 🍷',
    occupation: 'Vineyard Tasting Manager',
    education: 'Symbiosis International',
    height: '5\'6" (168cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'Long-term, open to short',
    photos: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Wine Tasting', 'Film Photography', 'Travel & Backpacking', 'Dog Lover'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'riya@vibematch.app',
    firstName: 'Riya',
    age: 22,
    birthDate: '2004-09-11',
    gender: 'woman',
    interestedIn: 'everyone',
    city: 'Nashik',
    locationLat: 19.9975,
    locationLng: 73.7898,
    bio: 'Energetic dancer, foodie, and music enthusiast in Nashik. Exploring sunset cafes along Gangapur Road and always down for good street food 💃🎶',
    occupation: 'Creative Stylist & Dancer',
    education: 'Nashik College of Fine Arts',
    height: '5\'4" (163cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'Long-term, open to short',
    datingIntent: 'Serious relationship or fun dating',
    relationshipPreference: 'Open to dating',
    photos: [
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Electronic Music', 'Indie Music', 'Food & Cooking', 'Vintage Thrift'],
    isVerified: true,
    isDemo: true,
    isAdult: true,
  },
  {
    email: 'sneha@vibematch.app',
    firstName: 'Sneha',
    age: 25,
    birthDate: '2001-01-30',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Aurangabad',
    locationLat: 19.8762,
    locationLng: 75.3433,
    bio: 'Architectural heritage researcher and fitness lover fascinated by Ajanta & Ellora caves. Passionate about slow travel, healthy living, and cinema 🏛️✨',
    occupation: 'Conservation Architect',
    education: 'BAMU Aurangabad',
    height: '5\'7" (170cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'Long-term partner',
    datingIntent: 'Long-term partner',
    relationshipPreference: 'Monogamous dating',
    photos: [
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Modern Art', 'Sourdough & Cooking', 'Book Club', 'Travel & Backpacking'],
    isVerified: true,
    isDemo: true,
    isAdult: true,
  },
  {
    email: 'priya.pune@vibematch.app',
    firstName: 'Priya',
    age: 27,
    birthDate: '1999-05-18',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Pune',
    locationLat: 18.5204,
    locationLng: 73.8567,
    bio: 'UI/UX lead obsessed with design, anime marathons, and rooftop dinners at Koregaon Park. Tell me your favorite Ghibli film or send your best playlist 🎨✨',
    occupation: 'Senior Product Designer',
    education: 'MIT Institute of Design, Pune',
    height: '5\'4" (163cm)',
    languages: ['Hindi', 'English', 'Marathi'],
    relationshipIntention: 'Long-term partner',
    datingIntent: 'Meaningful connection',
    relationshipPreference: 'Long-term relationship',
    photos: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Anime & Manga', 'Dog Lover', 'Specialty Coffee', 'Indie Music'],
    isVerified: true,
    isDemo: true,
    isAdult: true,
  },
  {
    email: 'tara.pune@vibematch.app',
    firstName: 'Tara',
    age: 23,
    birthDate: '2003-08-20',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Pune',
    locationLat: 18.5204,
    locationLng: 73.8567,
    bio: 'Creative tech developer and music lover in Kothrud. Passionate about indie gigs, creative generative art, and weekend drives to Lavasa 🚀🎧',
    occupation: 'Creative Technologist',
    education: 'Pune Institute of Computer Technology (PICT)',
    height: '5\'5" (165cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'Long-term, open to short',
    datingIntent: 'Dating & romance',
    relationshipPreference: 'Open-minded dating',
    photos: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Tech & Startups', 'Modern Art', 'Indie Music', 'Specialty Coffee'],
    isVerified: true,
    isDemo: true,
    isAdult: true,
  },
  {
    email: 'ananya@vibematch.app',
    firstName: 'Ananya',
    age: 25,
    birthDate: '2001-11-04',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Bengaluru',
    locationLat: 12.9716,
    locationLng: 77.5946,
    bio: 'Fintech product manager & half-marathoner. Sunday mornings mean 10k in Cubbon Park followed by specialty cold brews in Indiranagar 🏃‍♀️☕',
    occupation: 'Fintech Product Manager',
    education: 'BITS Pilani',
    height: '5\'6" (168cm)',
    languages: ['English', 'Hindi', 'Kannada'],
    relationshipIntention: 'Long-term partner',
    photos: [
      'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Running / 10k', 'Tech & Startups', 'Specialty Coffee', 'Yoga & Pilates'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'pooja@vibematch.app',
    firstName: 'Pooja',
    age: 26,
    birthDate: '2000-08-12',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Mumbai',
    locationLat: 19.0760,
    locationLng: 72.8777,
    bio: 'Pediatric resident doctor with a love for classical morning ragas, rooftop yoga, and spontaneous drives to Lonavala. Looking for warmth and good banter 🩺🎶',
    occupation: 'Resident Doctor',
    education: 'KEM Hospital & Seth GS Medical College',
    height: '5\'5" (165cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'Long-term partner',
    photos: [
      'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Yoga & Pilates', 'Book Club', 'Specialty Coffee', 'Cat Person'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'tanvi@vibematch.app',
    firstName: 'Tanvi',
    age: 24,
    birthDate: '2002-04-19',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Thane',
    locationLat: 19.2183,
    locationLng: 72.9781,
    bio: 'Creative brand strategist who loves live concerts, indie film festivals, and finding the best misal pav spots. Let\'s exchange song recommendations!',
    occupation: 'Brand Strategist',
    education: 'NMIMS Mumbai',
    height: '5\'4" (163cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'Short-term fun',
    photos: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Indie Music', 'Film Photography', 'Board Games', 'Travel & Backpacking'],
    isVerified: false,
    isDemo: true,
  },
  {
    email: 'shreya@vibematch.app',
    firstName: 'Shreya',
    age: 27,
    birthDate: '1999-06-25',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Pune',
    locationLat: 18.5204,
    locationLng: 73.8567,
    bio: 'Biochemist researching sustainable biopolymers. Weekend boulderer, proud dog mama to a golden retriever named Chai, and amateur sourdough baker 🐕🧗‍♀️',
    occupation: 'Biotech Scientist',
    education: 'IISER Pune',
    height: '5\'7" (170cm)',
    languages: ['Hindi', 'English', 'Marathi'],
    relationshipIntention: 'Long-term partner',
    photos: [
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Rock Climbing', 'Dog Lover', 'Sourdough & Cooking', 'Hiking & Camping'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'diya@vibematch.app',
    firstName: 'Diya',
    age: 22,
    birthDate: '2004-10-08',
    gender: 'woman',
    interestedIn: 'everyone',
    city: 'Nagpur',
    locationLat: 21.1458,
    locationLng: 79.0882,
    bio: 'Digital illustrator & comic artist. I spend too much time sketching in cafes and obsessing over Studio Ghibli aesthetics. Tarri poha lover for life 🎨',
    occupation: 'Freelance Illustrator',
    education: 'Sir J.J. Institute of Applied Art',
    height: '5\'2" (157cm)',
    languages: ['Hindi', 'Marathi', 'English'],
    relationshipIntention: 'New friends',
    photos: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Anime & Manga', 'Modern Art', 'Indie Music', 'Cat Person'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'kavya@vibematch.app',
    firstName: 'Kavya',
    age: 26,
    birthDate: '2000-02-14',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Mumbai',
    locationLat: 19.0760,
    locationLng: 72.8777,
    bio: 'Features journalist & coffee nerd in Bandra. Love sea walks along Carter Road, documentary discussions, and candle-lit acoustic sessions 🌿☕',
    occupation: 'Features Journalist & Essayist',
    education: 'St. Xavier\'s College, Mumbai',
    height: '5\'6" (168cm)',
    languages: ['Hindi', 'English', 'Marathi'],
    relationshipIntention: 'Long-term partner',
    datingIntent: 'Long-term dating',
    relationshipPreference: 'Exclusive connection',
    photos: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Book Club', 'Specialty Coffee', 'Film Photography', 'Travel & Backpacking'],
    isVerified: true,
    isDemo: true,
    isAdult: true,
  },
  {
    email: 'isha@vibematch.app',
    firstName: 'Isha',
    age: 24,
    birthDate: '2002-12-03',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Nashik',
    locationLat: 19.9975,
    locationLng: 73.7898,
    bio: 'Sound designer & electronic music creator in Nashik. Vinyl hunter, cozy night drives, and finding beauty in subtle vibrations 🎧⚡',
    occupation: 'Sound Designer & Musician',
    education: 'Symbiosis Media Institute',
    height: '5\'5" (165cm)',
    languages: ['Hindi', 'Marathi', 'English'],
    relationshipIntention: 'Short-term fun',
    datingIntent: 'Fun & romantic dates',
    relationshipPreference: 'Open to dating',
    photos: [
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Electronic Music', 'Indie Music', 'Vintage Thrift', 'Specialty Coffee'],
    isVerified: true,
    isDemo: true,
    isAdult: true,
  },
  {
    email: 'meera@vibematch.app',
    firstName: 'Meera',
    age: 24,
    birthDate: '2002-06-18',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Mumbai',
    locationLat: 19.0760,
    locationLng: 72.8777,
    bio: 'Ceramic artist and mindful lifestyle creator in South Mumbai. Big fan of pottery wheels, Marine Drive sunsets, and meaningful heart-to-hearts 🏺🌊',
    occupation: 'Ceramicist & Creative Coach',
    education: 'Sophia College Mumbai',
    height: '5\'4" (163cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'Long-term partner',
    datingIntent: 'Long-term connection',
    relationshipPreference: 'Romantic partnership',
    photos: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Modern Art', 'Yoga & Pilates', 'Book Club', 'Specialty Coffee'],
    isVerified: true,
    isDemo: true,
    isAdult: true,
  },
  {
    email: 'aditi@vibematch.app',
    firstName: 'Aditi',
    age: 27,
    birthDate: '1999-03-21',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Navi Mumbai',
    locationLat: 19.0330,
    locationLng: 73.0297,
    bio: 'Equity research analyst who balances balance sheets with weekend hiking trips to Rajmachi. I make great pasta from scratch and play mean Catan!',
    occupation: 'Equity Analyst, CFA',
    education: 'Narsee Monjee Institute',
    height: '5\'6" (168cm)',
    languages: ['Hindi', 'English', 'Marathi'],
    relationshipIntention: 'Long-term, open to short',
    photos: [
      'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Board Games', 'Hiking & Camping', 'Sourdough & Cooking', 'Running / 10k'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'simran@vibematch.app',
    firstName: 'Simran',
    age: 23,
    birthDate: '2003-08-09',
    gender: 'woman',
    interestedIn: 'men',
    city: 'Chandigarh',
    locationLat: 30.7333,
    locationLng: 76.7794,
    bio: 'Interior space stylist, road trip navigator, and proud golden retriever owner. Sukhna lake sunset walks and cold coffee are non-negotiable weekends 🐾',
    occupation: 'Spatial Designer',
    education: 'Panjab University',
    height: '5\'5" (165cm)',
    languages: ['Punjabi', 'Hindi', 'English'],
    relationshipIntention: 'Long-term partner',
    photos: [
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Dog Lover', 'Travel & Backpacking', 'Vintage Thrift', 'Specialty Coffee'],
    isVerified: true,
    isDemo: true,
  },

  // ================= 15 MALE FICTIONAL DEMO PROFILES =================
  {
    email: 'rohan@vibematch.app',
    firstName: 'Rohan',
    age: 25,
    birthDate: '2001-05-14',
    gender: 'man',
    interestedIn: 'women',
    city: 'Pune',
    locationLat: 18.5204,
    locationLng: 73.8567,
    bio: 'Tech lead building open source developer tools. When not coding, you will find me climbing forts in the Western Ghats or making pour-over Aeropress coffee ⛰️☕',
    occupation: 'Senior Full Stack Lead',
    education: 'COEP Pune',
    height: '5\'11" (180cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'Long-term partner',
    photos: [
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Hiking & Camping', 'Tech & Startups', 'Specialty Coffee', 'Rock Climbing'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'kabir@vibematch.app',
    firstName: 'Kabir',
    age: 27,
    birthDate: '1999-11-20',
    gender: 'man',
    interestedIn: 'women',
    city: 'Mumbai',
    locationLat: 19.0760,
    locationLng: 72.8777,
    bio: 'Independent documentary cinematographer shooting stories across India. Big believer in 35mm film grain, roadside chai stalls, and spontaneous road trips 🎥🎞️',
    occupation: 'Cinematographer & Director',
    education: 'Whistling Woods International',
    height: '6\'0" (183cm)',
    languages: ['Hindi', 'English', 'Punjabi'],
    relationshipIntention: 'Long-term, open to short',
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Film Photography', 'Indie Music', 'Travel & Backpacking', 'Modern Art'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'aarav@vibematch.app',
    firstName: 'Aarav',
    age: 24,
    birthDate: '2002-01-16',
    gender: 'man',
    interestedIn: 'women',
    city: 'Nashik',
    locationLat: 19.9975,
    locationLng: 73.7898,
    bio: 'Organic farm manager & artisanal sourdough baker in Gangapur. Weekend cyclist, dog rescue volunteer, and lover of slow Sunday breakfasts in the orchard 🥖🐕',
    occupation: 'Farm-to-Table Founder',
    education: 'Vasantrao Naik Agricultural Univ',
    height: '5\'10" (178cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'Long-term partner',
    photos: [
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Sourdough & Cooking', 'Dog Lover', 'Hiking & Camping', 'Wine Tasting'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'aditya.chhatrapati@vibematch.app',
    firstName: 'Aditya',
    age: 26,
    birthDate: '2000-07-04',
    gender: 'man',
    interestedIn: 'women',
    city: 'Chhatrapati Sambhajinagar',
    locationLat: 19.8762,
    locationLng: 75.3433,
    bio: 'Heritage structural engineer restoring ancient stone monuments. Avid long-distance cyclist, board games champion, and history podcast listener 🚴‍♂️🏰',
    occupation: 'Civil Restoration Engineer',
    education: 'Government College of Engineering',
    height: '5\'11" (180cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'New friends',
    photos: [
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Board Games', 'Running / 10k', 'Travel & Backpacking', 'Book Club'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'vikram@vibematch.app',
    firstName: 'Vikram',
    age: 28,
    birthDate: '1998-04-10',
    gender: 'man',
    interestedIn: 'women',
    city: 'Mumbai',
    locationLat: 19.0760,
    locationLng: 72.8777,
    bio: 'Investment partner focused on climate technology. Early morning squash player, espresso purist, and lover of jazz bars in Colaba 🎾☕',
    occupation: 'Venture Capital Associate',
    education: 'IIT Bombay & IIM Ahmedabad',
    height: '6\'1" (185cm)',
    languages: ['Hindi', 'English'],
    relationshipIntention: 'Long-term partner',
    photos: [
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Tech & Startups', 'Running / 10k', 'Wine Tasting', 'Book Club'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'arjun@vibematch.app',
    firstName: 'Arjun',
    age: 24,
    birthDate: '2002-12-28',
    gender: 'man',
    interestedIn: 'everyone',
    city: 'Pune',
    locationLat: 18.5204,
    locationLng: 73.8567,
    bio: '3D game animator crafting fantasy RPG worlds. Big anime fan, synthesizers collector, and always hunting down late-night burger joints in KP 🎮🍔',
    occupation: 'Game Animator & 3D Artist',
    education: 'DSK International Campus Pune',
    height: '5\'9" (175cm)',
    languages: ['Hindi', 'English', 'Marathi'],
    relationshipIntention: 'Still figuring it out',
    photos: [
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Anime & Manga', 'Electronic Music', 'Tech & Startups', 'Modern Art'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'siddharth@vibematch.app',
    firstName: 'Siddharth',
    age: 26,
    birthDate: '2000-09-03',
    gender: 'man',
    interestedIn: 'women',
    city: 'Bengaluru',
    locationLat: 12.9716,
    locationLng: 77.5946,
    bio: 'AI researcher working on multimodal vision models. Weekend boulderer at Equilibrium, pour-over coffee geek, and vinyl record collector 🧗‍♂️🎧',
    occupation: 'AI Research Scientist',
    education: 'IIIT Hyderabad',
    height: '6\'0" (183cm)',
    languages: ['Hindi', 'English', 'Telugu'],
    relationshipIntention: 'Long-term partner',
    photos: [
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Rock Climbing', 'Specialty Coffee', 'Tech & Startups', 'Indie Music'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'yash@vibematch.app',
    firstName: 'Yash',
    age: 25,
    birthDate: '2001-03-17',
    gender: 'man',
    interestedIn: 'women',
    city: 'Thane',
    locationLat: 19.2183,
    locationLng: 72.9781,
    bio: 'Chef and sourdough bistro owner. I will cook you the crispiest artisanal pizzas and tell you stories behind every spice. Upendra road food walks fan 🍕👨‍🍳',
    occupation: 'Head Chef & Bistro Owner',
    education: 'IHM Mumbai',
    height: '5\'10" (178cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'Long-term partner',
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Sourdough & Cooking', 'Dog Lover', 'Wine Tasting', 'Indie Music'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'dev@vibematch.app',
    firstName: 'Dev',
    age: 27,
    birthDate: '1999-08-29',
    gender: 'man',
    interestedIn: 'women',
    city: 'Pune',
    locationLat: 18.5204,
    locationLng: 73.8567,
    bio: 'Indie acoustic guitarist and singer-songwriter. You will either find me recording chords in my home studio or playing open mics at Viman Nagar 🎸✨',
    occupation: 'Music Producer & Songwriter',
    education: 'Pune University',
    height: '5\'11" (180cm)',
    languages: ['Hindi', 'Marathi', 'English'],
    relationshipIntention: 'Short-term fun',
    photos: [
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Indie Music', 'Film Photography', 'Vintage Thrift', 'Specialty Coffee'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'sameer@vibematch.app',
    firstName: 'Sameer',
    age: 26,
    birthDate: '2000-02-11',
    gender: 'man',
    interestedIn: 'women',
    city: 'Nagpur',
    locationLat: 21.1458,
    locationLng: 79.0882,
    bio: 'Wildlife biologist & nature photographer tracking tiger corridors in Tadoba and Pench. Let\'s watch stars around a campfire and share jungle tales 🐅⛺',
    occupation: 'Wildlife Conservationist',
    education: 'Nagpur University',
    height: '6\'0" (183cm)',
    languages: ['Hindi', 'Marathi', 'English'],
    relationshipIntention: 'Long-term partner',
    photos: [
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Hiking & Camping', 'Film Photography', 'Travel & Backpacking', 'Dog Lover'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'kunal@vibematch.app',
    firstName: 'Kunal',
    age: 25,
    birthDate: '2001-06-20',
    gender: 'man',
    interestedIn: 'women',
    city: 'Mumbai',
    locationLat: 19.0760,
    locationLng: 72.8777,
    bio: 'Creative ad copywriter and weekend stand-up comedian. If you appreciate puns, dry humor, and deep conversations over cutting chai, swipe right! ☕🎙️',
    occupation: 'Senior Copywriter',
    education: 'St. Xavier\'s College Mumbai',
    height: '5\'8" (173cm)',
    languages: ['Hindi', 'English', 'Gujarati'],
    relationshipIntention: 'New friends',
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Board Games', 'Book Club', 'Dog Lover', 'Indie Music'],
    isVerified: false,
    isDemo: true,
  },
  {
    email: 'varun@vibematch.app',
    firstName: 'Varun',
    age: 28,
    birthDate: '1998-10-15',
    gender: 'man',
    interestedIn: 'women',
    city: 'Delhi',
    locationLat: 28.6139,
    locationLng: 77.2090,
    bio: 'Tech policy lawyer by day, amateur jazz pianist by night. Khan Market book shopper, lover of winter sunshine, and passionate about art galleries 🎹📖',
    occupation: 'Legal Counsel',
    education: 'National Law School of India',
    height: '6\'1" (185cm)',
    languages: ['Hindi', 'English'],
    relationshipIntention: 'Long-term partner',
    photos: [
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Modern Art', 'Specialty Coffee', 'Book Club', 'Wine Tasting'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'harsh@vibematch.app',
    firstName: 'Harsh',
    age: 24,
    birthDate: '2002-04-02',
    gender: 'man',
    interestedIn: 'women',
    city: 'Pune',
    locationLat: 18.5204,
    locationLng: 73.8567,
    bio: 'Sports physiotherapist and calisthenics trainer in Aundh. Passionate about holistic mobility, outdoor trail runs, and making healthy meals that actually taste great 🥗🏃‍♂️',
    occupation: 'Sports Physiotherapist',
    education: 'Bharati Vidyapeeth Pune',
    height: '5\'11" (180cm)',
    languages: ['Marathi', 'Hindi', 'English'],
    relationshipIntention: 'Long-term, open to short',
    photos: [
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Running / 10k', 'Yoga & Pilates', 'Hiking & Camping', 'Rock Climbing'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'aryan@vibematch.app',
    firstName: 'Aryan',
    age: 25,
    birthDate: '2001-08-19',
    gender: 'man',
    interestedIn: 'women',
    city: 'Navi Mumbai',
    locationLat: 19.0330,
    locationLng: 73.0297,
    bio: 'Renewable energy design engineer working on solar microgrids. Astrophotography nerd who loves driving into the hills on moonless nights to shoot constellations 🔭✨',
    occupation: 'Clean Energy Engineer',
    education: 'VJTI Mumbai',
    height: '5\'10" (178cm)',
    languages: ['Hindi', 'English', 'Marathi'],
    relationshipIntention: 'Long-term partner',
    photos: [
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Tech & Startups', 'Film Photography', 'Hiking & Camping', 'Travel & Backpacking'],
    isVerified: true,
    isDemo: true,
  },
  {
    email: 'nikhil@vibematch.app',
    firstName: 'Nikhil',
    age: 27,
    birthDate: '1999-01-24',
    gender: 'man',
    interestedIn: 'women',
    city: 'Mumbai',
    locationLat: 19.0760,
    locationLng: 72.8777,
    bio: 'Architectural furniture craftsman creating minimalist wooden tables. Cat dad to a tuxedo cat named Oreo, filter coffee lover, and weekend thrift hunter 🪵☕🐈',
    occupation: 'Bespoke Furniture Designer',
    education: 'IDC School of Design, IIT Bombay',
    height: '5\'11" (180cm)',
    languages: ['Hindi', 'English', 'Marathi'],
    relationshipIntention: 'Still figuring it out',
    photos: [
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    ],
    interests: ['Modern Art', 'Cat Person', 'Vintage Thrift', 'Specialty Coffee'],
    isVerified: true,
    isDemo: true,
  },
];

export interface SeedAICompanion {
  id: string;
  name: string;
  age: number;
  personality: string;
  interests: string[];
  avatar: string;
  greeting: string;
  suggestedQuestions: string[];
}

export const SEED_AI_COMPANIONS: SeedAICompanion[] = [
  {
    id: 'ai-aanya',
    name: 'Aanya AI',
    age: 23,
    personality: 'Cute, friendly, cheerful',
    interests: ['Music', 'Movies', 'Travel'],
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    greeting: "Hi 😊 I'm Aanya, an AI companion created for VibeMatch. Want to chat?",
    suggestedQuestions: [
      "What's your favorite movie?",
      "What do you do in your free time?",
      "Where would you love to travel?",
      "What music do you like?",
      "Tell me something interesting about you.",
      "How was your day?",
    ],
  },
  {
    id: 'ai-meera',
    name: 'Meera AI',
    age: 24,
    personality: 'Calm, sweet, thoughtful',
    interests: ['Books', 'Coffee', 'Photography'],
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    greeting: "Hello ☕ I'm Meera, an AI companion on VibeMatch. I love calm conversations, good reads, and photography. How is your day going?",
    suggestedQuestions: [
      "What book or story inspires you most?",
      "How do you like your coffee?",
      "What is a place that brings you peace?",
      "Do you enjoy photography or nature walks?",
      "What makes you smile?",
    ],
  },
  {
    id: 'ai-riya',
    name: 'Riya AI',
    age: 22,
    personality: 'Fun, energetic, playful',
    interests: ['Dance', 'Music', 'Food'],
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
    greeting: "Hey there! 🎉 I'm Riya, your energetic AI companion on VibeMatch! Ready to talk about dance, good beats, or mouthwatering food?",
    suggestedQuestions: [
      "What track always gets you dancing?",
      "What's the best street food you've ever had?",
      "Beach date or amusement park?",
      "Tell me a funny story from this week!",
      "What's your favorite festival vibe?",
    ],
  },
  {
    id: 'ai-sneha',
    name: 'Sneha AI',
    age: 25,
    personality: 'Friendly, confident, supportive',
    interests: ['Fitness', 'Travel', 'Movies'],
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    greeting: "Hi! 🌟 I'm Sneha, an AI companion built for VibeMatch. I'm here to cheer you on, talk about fitness, travel adventures, or cinema. What's on your mind?",
    suggestedQuestions: [
      "What's your current fitness or wellness goal?",
      "If you could hop on a plane right now, where to?",
      "What's the best movie you watched recently?",
      "How do you stay motivated when things get busy?",
      "What makes a truly great conversation?",
    ],
  },
  {
    id: 'ai-tara',
    name: 'Tara AI',
    age: 23,
    personality: 'Creative, funny, curious',
    interests: ['Art', 'Technology', 'Music'],
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    greeting: "Hey! 🎨 I'm Tara, an AI companion on VibeMatch. I'm always curious about creative projects, tech ideas, and indie music. What are you into?",
    suggestedQuestions: [
      "What creative project or hobby excites you?",
      "What futuristic tech do you wish existed today?",
      "What's your favorite song lyric?",
      "Do you prefer museum dates or acoustic concerts?",
      "Tell me something you learned recently!",
    ],
  },
];
