import React, { useState, useEffect, useRef } from 'react';
import {
  Bot,
  Sparkles,
  Send,
  Info,
  ShieldCheck,
  Heart,
  MessageSquare,
  ArrowLeft,
  Flame,
  Brain,
  Smile,
} from 'lucide-react';
import { AICompanion, AIMessage } from '../types';
import { api } from '../api/client';

export const AICompanionsView: React.FC = () => {
  const [companions, setCompanions] = useState<AICompanion[]>([]);
  const [activeCompanion, setActiveCompanion] = useState<AICompanion | null>(null);
  const [messages, setMessages] = useState<AIMessage[]>([]);
  const [inputMessage, setInputMessage] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [isSending, setIsSending] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    loadCompanions();
  }, []);

  const loadCompanions = async () => {
    setIsLoading(true);
    try {
      const data = await api.getAICompanions();
      setCompanions(data);
    } catch (err) {
      console.error('Error loading AI companions:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const openCompanionChat = async (companion: AICompanion) => {
    setActiveCompanion(companion);
    setIsLoading(true);
    try {
      const data = await api.getAIConversation(companion.id);
      setMessages(data.messages || []);
    } catch (err) {
      console.error('Error opening AI conversation:', err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isSending]);

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputMessage.trim() || !activeCompanion || isSending) return;

    const userText = inputMessage.trim();
    setInputMessage('');
    setIsSending(true);

    // Optimistic user message
    const tempUserMsg: AIMessage = {
      id: `temp-${Date.now()}`,
      conversationId: activeCompanion.id,
      senderType: 'user',
      content: userText,
      createdAt: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, tempUserMsg]);

    try {
      const res = await api.sendAIMessage(activeCompanion.id, userText);
      if (res.success && res.aiMessage) {
        setMessages((prev) => [
          ...prev.filter((m) => m.id !== tempUserMsg.id),
          res.userMessage,
          res.aiMessage,
        ]);
      }
    } catch (err) {
      console.error('Failed to send AI message:', err);
    } finally {
      setIsSending(false);
    }
  };

  return (
    <div id="ai-companions-container" className="p-4 sm:p-6 max-w-6xl mx-auto space-y-6 text-white pb-24">
      {/* Header Banner */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-purple-950/50 via-[#161224] to-[#121620] border border-purple-500/20 p-6 sm:p-8 shadow-2xl">
        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/20 border border-purple-500/30 text-purple-300 text-xs font-bold tracking-wide">
              <Bot className="w-4 h-4 text-purple-400" />
              <span>AI COMPANIONS</span>
              <span className="bg-purple-500/40 text-purple-200 text-[10px] px-1.5 py-0.2 rounded font-semibold">
                VIRTUAL PERSONALITIES
              </span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight bg-gradient-to-r from-white via-purple-100 to-rose-200 bg-clip-text text-transparent">
              Virtual Companions & Safe Simulation
            </h1>
            <p className="text-xs sm:text-sm text-gray-300 max-w-2xl leading-relaxed">
              Engage in conversational practice, deep dialogue, and playful banter with specialized AI personalities. 
              Always transparent, always respectful.
            </p>
          </div>

          {/* Mandatory AI Transparency Badge */}
          <div className="flex items-center gap-2.5 px-4 py-3 rounded-2xl bg-black/40 border border-purple-500/20 text-xs text-purple-200 backdrop-blur-md">
            <ShieldCheck className="w-5 h-5 text-purple-400 shrink-0" />
            <div>
              <p className="font-bold text-white">Full Transparency</p>
              <p className="text-[11px] text-gray-400">All responses are generated by AI</p>
            </div>
          </div>
        </div>
      </div>

      {/* Main View: List or Active Chat */}
      {!activeCompanion ? (
        // ================= COMPANION SELECTOR CARDS =================
        <div className="space-y-4">
          <h2 className="text-lg font-bold text-gray-200 flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-purple-400" />
            <span>Select an AI Companion</span>
          </h2>

          {isLoading ? (
            <div className="text-center py-20 text-gray-400 text-sm animate-pulse">
              Loading AI Companions...
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {companions.map((comp) => (
                <div
                  key={comp.id}
                  id={`ai-card-${comp.id}`}
                  className="group relative rounded-3xl bg-[#141824] border border-purple-500/20 overflow-hidden shadow-xl hover:border-purple-500/50 transition-all flex flex-col justify-between"
                >
                  <div className="relative aspect-[4/3] w-full overflow-hidden bg-gray-950">
                    <img
                      src={comp.avatar}
                      alt={comp.name}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                      referrerPolicy="no-referrer"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-[#141824] via-[#141824]/30 to-transparent" />

                    {/* AI Companion Badge */}
                    <div className="absolute top-3 left-3 flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-purple-900/80 backdrop-blur-md border border-purple-400/30 text-purple-200 text-[11px] font-bold">
                      <Bot className="w-3.5 h-3.5 text-purple-300" />
                      <span>🤖 AI Companion</span>
                    </div>

                    <div className="absolute bottom-3 left-3 right-3">
                      <span className="text-[10px] uppercase tracking-wider font-extrabold px-2 py-0.5 rounded bg-black/60 text-purple-300 border border-purple-500/20">
                        {comp.personality}
                      </span>
                    </div>
                  </div>

                  <div className="p-5 flex-1 flex flex-col justify-between space-y-4">
                    <div>
                      <div className="flex items-center justify-between">
                        <h3 className="text-xl font-bold text-white flex items-center gap-2">
                          <span>{comp.name}</span>
                          <span className="text-xs text-purple-400 font-normal">
                            ({comp.age})
                          </span>
                        </h3>
                      </div>
                      <p className="text-xs text-purple-300/80 font-medium mt-0.5">
                        {comp.personality}
                      </p>

                      {/* Topic Tags */}
                      <div className="flex flex-wrap gap-1.5 mt-3">
                        {comp.interests.map((t, idx) => (
                          <span
                            key={idx}
                            className="px-2 py-0.5 rounded-lg bg-purple-500/10 border border-purple-500/20 text-[10px] text-purple-300 font-medium"
                          >
                            #{t}
                          </span>
                        ))}
                      </div>
                    </div>

                    {/* Greeting Preview & Button */}
                    <div className="pt-3 border-t border-white/5 space-y-3">
                      <div className="p-2.5 rounded-xl bg-purple-950/20 border border-purple-500/10 text-xs text-purple-200 italic">
                        "{comp.greeting}"
                      </div>

                      <button
                        id={`btn-chat-ai-${comp.id}`}
                        onClick={() => openCompanionChat(comp)}
                        className="w-full py-2.5 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white text-xs font-bold flex items-center justify-center gap-2 shadow-lg shadow-purple-600/30 transition-all"
                      >
                        <MessageSquare className="w-4 h-4" />
                        <span>Chat with {comp.name}</span>
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      ) : (
        // ================= ACTIVE CHAT INTERFACE =================
        <div className="bg-[#141824] border border-purple-500/20 rounded-3xl overflow-hidden shadow-2xl flex flex-col h-[650px]">
          {/* Chat Header */}
          <div className="p-4 bg-[#0F131C] border-b border-white/10 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <button
                id="btn-back-ai-list"
                onClick={() => setActiveCompanion(null)}
                className="p-2 rounded-xl bg-white/5 hover:bg-white/10 text-gray-300 hover:text-white transition-colors"
              >
                <ArrowLeft className="w-4 h-4" />
              </button>

              <div className="relative">
                <img
                  src={activeCompanion.avatar}
                  alt={activeCompanion.name}
                  className="w-10 h-10 rounded-full object-cover border-2 border-purple-400"
                  referrerPolicy="no-referrer"
                />
                <span className="absolute bottom-0 right-0 w-3 h-3 rounded-full bg-emerald-400 border-2 border-[#0F131C]" />
              </div>

              <div>
                <div className="flex items-center gap-2">
                  <h3 className="font-bold text-white text-sm">
                    {activeCompanion.name}
                  </h3>
                  <span className="flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-purple-500/20 border border-purple-500/30 text-purple-300">
                    <Bot className="w-3 h-3" />
                    AI Companion
                  </span>
                </div>
                <p className="text-[11px] text-gray-400">
                  {activeCompanion.personality} • Virtual Simulation
                </p>
              </div>
            </div>

            <div className="text-right hidden sm:block">
              <span className="text-[10px] text-purple-300 bg-purple-950/40 border border-purple-500/20 px-2.5 py-1 rounded-full">
                Fictional AI Character
              </span>
            </div>
          </div>

          {/* Mandatory Persistent AI Transparency Banner */}
          <div className="bg-purple-950/50 border-b border-purple-500/20 px-4 py-2 flex items-center gap-2 text-xs text-purple-200">
            <Info className="w-4 h-4 text-purple-400 shrink-0" />
            <span className="font-medium text-[11px] leading-tight">
              Notice: You are chatting with an AI companion. This is a fictional simulation and not a real person.
            </span>
          </div>

          {/* Messages Feed */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            {messages.map((msg) => {
              const isUser = msg.senderType === 'user';
              return (
                <div
                  key={msg.id}
                  className={`flex items-end gap-2.5 ${isUser ? 'justify-end' : 'justify-start'}`}
                >
                  {!isUser && (
                    <img
                      src={activeCompanion.avatar}
                      alt={activeCompanion.name}
                      className="w-7 h-7 rounded-full object-cover border border-purple-400 shrink-0"
                      referrerPolicy="no-referrer"
                    />
                  )}

                  <div
                    className={`max-w-[80%] sm:max-w-md rounded-2xl px-4 py-3 text-xs sm:text-sm leading-relaxed ${
                      isUser
                        ? 'bg-gradient-to-r from-purple-600 to-indigo-600 text-white rounded-br-sm shadow-md'
                        : 'bg-[#1C2233] text-gray-200 border border-purple-500/20 rounded-bl-sm shadow-md'
                    }`}
                  >
                    {!isUser && (
                      <div className="flex items-center gap-1 text-[10px] font-bold text-purple-300 mb-1">
                        <Bot className="w-3 h-3" />
                        <span>{activeCompanion.name} (AI)</span>
                      </div>
                    )}
                    <p className="whitespace-pre-wrap">{msg.content}</p>
                    <span className="block text-[10px] text-white/50 text-right mt-1">
                      {new Date(msg.createdAt).toLocaleTimeString([], {
                        hour: '2-digit',
                        minute: '2-digit',
                      })}
                    </span>
                  </div>
                </div>
              );
            })}

            {isSending && (
              <div className="flex items-end gap-2.5 justify-start">
                <img
                  src={activeCompanion.avatar}
                  alt={activeCompanion.name}
                  className="w-7 h-7 rounded-full object-cover border border-purple-400 shrink-0"
                  referrerPolicy="no-referrer"
                />
                <div className="bg-[#1C2233] text-purple-300 border border-purple-500/20 rounded-2xl rounded-bl-sm px-4 py-2.5 text-xs flex items-center gap-1.5">
                  <span className="w-1.5 h-1.5 rounded-full bg-purple-400 animate-bounce" />
                  <span className="w-1.5 h-1.5 rounded-full bg-purple-400 animate-bounce delay-100" />
                  <span className="w-1.5 h-1.5 rounded-full bg-purple-400 animate-bounce delay-200" />
                  <span className="ml-1 text-[11px] font-medium">
                    {activeCompanion.name} is typing...
                  </span>
                </div>
              </div>
            )}

            <div ref={messagesEndRef} />
          </div>

          {/* Chat Input Bar */}
          <form
            onSubmit={handleSendMessage}
            className="p-3 bg-[#0F131C] border-t border-white/10 flex items-center gap-2"
          >
            <input
              id="ai-message-input"
              type="text"
              value={inputMessage}
              onChange={(e) => setInputMessage(e.target.value)}
              placeholder={`Message ${activeCompanion.name}...`}
              className="flex-1 bg-[#1A2030] border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-gray-400 focus:outline-none focus:border-purple-500"
            />
            <button
              id="btn-send-ai-message"
              type="submit"
              disabled={!inputMessage.trim() || isSending}
              className="p-2.5 rounded-xl bg-purple-600 hover:bg-purple-700 disabled:opacity-50 text-white transition-colors"
            >
              <Send className="w-4 h-4" />
            </button>
          </form>
        </div>
      )}
    </div>
  );
};
